version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "python" # Avoid PRs trying to bump interpreter itself
    versioning-strategy: increase
    groups:
      poetry-deps:
        patterns:
          - "*"
    commit-message:
      prefix: "deps"
      include: "scope"
